### ISSUE TITLE
Package shouldn't use --filesystem=~/.CommanderGenius:create

### ISSUE THREAD

**Issue by ssokolow** [flathub/io.sourceforge.clonekeenplus#1]
The permissions section of the [App Requirements](https://github.com/flathub/flathub/wiki/App-Requirements) page for flathub says as follows:

> Do not attempt to retain configs from non-flatpak installations. While possible it is recommended that flatpak installs stay self-contained.

You should instead be using `--persist=.CommanderGenius` to map what Commander Genius sees as `~/.CommanderGenius` to `~/.var/app/io.sourceforge.clonekeenplus/.CommanderGenius` if the upstream codebase doesn't provide flags for relocating it into XDG Base Directory Specification paths.

Among other things, I believe that's necessary for `flatpak remove --delete-data` to successfully remove downloaded game data when asked.

(And, more personally, it annoys me to have to go into Flatseal and manually make that change before first launch.)

**Comment by gerstrong** [comment]
I have adjusted the Search Path settings. It should be fixed now. Feel free to reopen this ticket if you still see problems.
